name: 🗓️ Daily Reviews Feed

on:
  # Run every day at midnight UTC
  schedule:
    - cron: '0 0 * * *'
  # Allow manual triggers
  workflow_dispatch:

jobs:
  generate-and-upload:
    runs-on: ubuntu-latest

    steps:
      # 1) Check out your repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas faker python-dateutil tqdm google-cloud-storage

      # 4) Authenticate to GCP using your service-account JSON
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id:      ${{ secrets.GCP_PROJECT }}

      # 5) Generate the reviews XML and upload it
      - name: Generate & Upload Reviews
        env:
          CSV_URL:     ${{ secrets.CSV_URL }}
          GCS_BUCKET:  ${{ secrets.GCS_BUCKET }}
        run: |
          python main.py \
            --csv-source "$CSV_URL" \
            --output "leela_reviews.xml" \
            --n-per-product 2 \
            --gcs-bucket "$GCS_BUCKET" \
            --gcs-dest "Googlefinal/leela_reviews.xml"
